version: '2'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - '$PWD/mysql:/etc/mysql'
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
    container_name: mysql_club
  redis:
    image: redis
    ports: 
      - '6379:6379'
    container_name: redis_club