version: '2'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - '$PWD/conf/mysql:/etc/mysql'
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
    container_name: mysql_bbs
  redis:
    image: redis
    ports: 
      - '6379:6379'
    container_name: redis_bbs
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes: 
      - '$PWD/conf/nginx:/etc/nginx'
    container_name: nginx_bbs